apiVersion: v1
kind: Secret
metadata:
  name: shkeeper-btc-key
  namespace: {{ .Values.namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
