{{- if .Values.eth_fullnode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum-nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf.template: |
    server {
        listen 8081;
        if ($http_X_SHKEEPER_BACKEND_KEY != ${SHKEEPER_BACKEND_KEY}) { return 403 "Bad key!\n"; }
        location / {
            root /datadir/keystore;
            autoindex on;
        }
    }
  nginx.conf: |
    user  root;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        include /etc/nginx/conf.d/*.conf;
    }
{{- end }}